// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

// Справочник валют
type AppCurrency struct {
	// Уникальный код валюты (ISO)
	Code string
	// Курс валюты относительно базовой
	Rate float32
}
