// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: queries.sql

package db

import (
	"context"
)

const getAllCurrencies = `-- name: GetAllCurrencies :many
SELECT code, rate FROM app.currencies
`

func (q *Queries) GetAllCurrencies(ctx context.Context) ([]AppCurrency, error) {
	rows, err := q.db.Query(ctx, getAllCurrencies)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AppCurrency
	for rows.Next() {
		var i AppCurrency
		if err := rows.Scan(&i.Code, &i.Rate); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getCurrency = `-- name: GetCurrency :one
SELECT code, rate FROM app.currencies WHERE code=$1
`

func (q *Queries) GetCurrency(ctx context.Context, code string) (AppCurrency, error) {
	row := q.db.QueryRow(ctx, getCurrency, code)
	var i AppCurrency
	err := row.Scan(&i.Code, &i.Rate)
	return i, err
}
